### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by starock** [FlorentFlament/ym2149-sndh#1]
First of all, thank you for the code.

When I make this project something worng, how can I fix it? THX :)

$ make
avr-gcc -DF_CPU=16000000  -mmcu=atmega328p -Wall -Werror -Wextra -Ofast -c main.c -o main.o
main.c: In function ‘main’:
main.c:157:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
       smp_state = SMP_TSLO;
                 ^
main.c:158:5: note: here
     case SMP_TSLO:
     ^~~~
main.c:162:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
       smp_state = SMP_WAIT;
                 ^
main.c:163:5: note: here
     case SMP_WAIT:
     ^~~~
main.c:165:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
       smp_state = SMP_ADDR;
                 ^
main.c:166:5: note: here
     case SMP_ADDR:
     ^~~~
main.c:171:17: error: this statement may fall through [-Werror=implicit-fallthrough=]
       smp_state = SMP_VAL; // Address is valid
                 ^
main.c:172:5: note: here
     case SMP_VAL:
     ^~~~
main.c:199:16: error: this statement may fall through [-Werror=implicit-fallthrough=]
       rx_state = RX_CHUNKLO;
                ^
main.c:200:5: note: here
     case RX_CHUNKLO:
     ^~~~
cc1: all warnings being treated as errors
make: *** [main.o] Error 1

**Comment by FlorentFlament** [comment]
Hi,
It's been a while, but I just fixed this issue.
Apparently gcc (I think I read since gcc 7) now complains when not breaking between case statements. It has to be expressed explicitly with a `/* FALLTHRU */` comment or equivalent:
https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html (-Wimplicit-fallthrough=n)
