### ISSUE TITLE
List of components used

### ISSUE THREAD

**Issue by emoon** [FlorentFlament/ym2149-sndh#3]
I wonder if it would be possible to get a BOM (Bill of materials) used for the hardware player? :)

**Comment by FlorentFlament** [comment]
Well, @Villadelfia made a PCB of the hardware ( see https://youtu.be/DkG42CIaaN0 ). I guess you could ask him if he would be willing to share his BOM. Other than, that the components are quite standard.

Happy hacking !

**Comment by Villadelfia** [comment]
https://easyeda.com/randy.thiemann/ym2149-breakout PCB and BOM there.

**Comment by emoon** [comment]
Awesome! Thanks :)
